pipeline {
    agent {
        docker {
            image 'node:18.18.1-alpine3.18' 
            args '-p 5173:5173' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
    }
}